# Generated by Django 4.2.4 on 2023-09-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
                ('time_zone', models.CharField(max_length=20)),
                ('isd_code', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='localstore.country')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Company Start')),
                ('is_active', models.BooleanField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localstore.country')),
            ],
        ),
    ]
