# Generated by Django 4.2.4 on 2023-09-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localstore', '0002_alter_country_isd_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
