# Generated by Django 4.2.4 on 2023-09-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localstore', '0003_alter_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='localstore.state'),
        ),
    ]
